spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itheima
    username: root
    password: 727399301
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        resetEnable: false

      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false

  #    filters: stat,wall
#    tomcat:
#      max-active:
  jdbc:
    template:
      query-timeout: 5
  boot:
    admin:
      client:
        url: http://localhost:8888


  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: # 如果未单独配置默认为空即可
    timeout: 1000
    client-type: jedis
    jedis:
      pool:
        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0


# 配置mybatis规则、使用MyBatisPlus则此项配置无效
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true

info:
  appName: boot-admin
  version: 2.0.1
  mavenProjectName: @project.artifactId@  #使用@@可以获取maven的pom文件值
  mavenProjectVersion: @project.version@